# Generated by Django 4.2.2 on 2023-06-30 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CostDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ordinary",
                    models.DecimalField(
                        decimal_places=2,
                        default=200,
                        max_digits=8,
                        verbose_name="Стоимость обычной доставки",
                    ),
                ),
                (
                    "express",
                    models.DecimalField(
                        decimal_places=2,
                        default=500,
                        max_digits=8,
                        verbose_name="Стоимость экспресс доставки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Цена за доставку",
                "verbose_name_plural": "Цены за доставку",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "createdAt",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "fullName",
                    models.CharField(
                        default="", max_length=20, verbose_name="Полное имя"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        default="", max_length=254, verbose_name="Электронная почта"
                    ),
                ),
                (
                    "phone",
                    models.CharField(default="", max_length=20, verbose_name="Телефон"),
                ),
                (
                    "deliveryType",
                    models.CharField(
                        default="free", max_length=20, verbose_name="Тип доставки"
                    ),
                ),
                (
                    "paymentType",
                    models.CharField(
                        default="online", max_length=20, verbose_name="Тип платежа"
                    ),
                ),
                (
                    "totalCost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        verbose_name="Итоговая стоимость",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="accepted", max_length=20, verbose_name="Статус"
                    ),
                ),
                (
                    "city",
                    models.CharField(default="", max_length=20, verbose_name="Город"),
                ),
                (
                    "address",
                    models.CharField(default="", max_length=20, verbose_name="Адрес"),
                ),
                (
                    "paymentError",
                    models.CharField(
                        default="", max_length=20, verbose_name="Ошибка оплаты"
                    ),
                ),
                (
                    "created",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        related_name="products",
                        to="catalog.product",
                        verbose_name="Продукты",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
                "ordering": ("id",),
            },
        ),
    ]
