# Generated by Django 4.2.2 on 2023-06-30 11:08

import catalog.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="Название категории"
                    ),
                ),
            ],
            options={
                "verbose_name": "Родительская категория",
                "verbose_name_plural": "Родительские категории",
                "ordering": ("title",),
            },
        ),
        migrations.CreateModel(
            name="ImageCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "src",
                    models.ImageField(
                        default="default.jpg",
                        upload_to="catalog/categories/categories/",
                        verbose_name="Ссылка",
                    ),
                ),
                (
                    "alt",
                    models.CharField(
                        default="Без описания", max_length=128, verbose_name="Описание"
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение категорий",
                "verbose_name_plural": "Изображения категорий",
            },
        ),
        migrations.CreateModel(
            name="ImageSubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "src",
                    models.ImageField(
                        default="default.jpg",
                        upload_to="catalog/categories/subcategories/",
                        verbose_name="Ссылка",
                    ),
                ),
                (
                    "alt",
                    models.CharField(
                        default="Без описания", max_length=128, verbose_name="Описание"
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение дочерних категорий",
                "verbose_name_plural": "Изображения дочерних категорий",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        verbose_name="Полная стоимость",
                    ),
                ),
                ("count", models.IntegerField(default=1, verbose_name="Количество")),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Название"
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "fullDescription",
                    models.TextField(db_index=True, verbose_name="Полное описание"),
                ),
                (
                    "freeDelivery",
                    models.BooleanField(
                        default=True, verbose_name="Бесплатная доставка"
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=3,
                        max_length=10,
                        verbose_name="Рейтинг",
                    ),
                ),
                (
                    "count_buy",
                    models.IntegerField(default=0, verbose_name="Количество покупок"),
                ),
                (
                    "popular",
                    models.BooleanField(default=False, verbose_name="Популярный"),
                ),
                (
                    "limited",
                    models.BooleanField(default=False, verbose_name="Ограниченный"),
                ),
                (
                    "for_banner",
                    models.BooleanField(default=False, verbose_name="Для баннера"),
                ),
                (
                    "preview",
                    models.ImageField(
                        upload_to="catalog/products/", verbose_name="Изображение"
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Название"
                    ),
                ),
            ],
            options={
                "verbose_name": "Тэг",
                "verbose_name_plural": "Тэги",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="Название категории"
                    ),
                ),
                (
                    "id_parrent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="catalog.category",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategory",
                        to="catalog.imagesubcategory",
                        verbose_name="Изображение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Дочерняя категория",
                "verbose_name_plural": "Дочернии категории",
                "ordering": ("title",),
            },
        ),
        migrations.CreateModel(
            name="Specification",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Параметр"
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Значение"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specifications",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Параметр продукта",
                "verbose_name_plural": "Параметры продукта",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "salePrice",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        verbose_name="Скидочная стоимость",
                    ),
                ),
                ("dateFrom", models.DateTimeField()),
                ("dateTo", models.DateTimeField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales",
                        to="catalog.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductReview",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("text", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "rate",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MaxValueValidator(10),
                            django.core.validators.MinValueValidator(1),
                        ],
                        verbose_name="Рейтинг",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="catalog.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
                "ordering": ("date",),
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "src",
                    models.ImageField(
                        upload_to=catalog.models.product_images_directory_path,
                        verbose_name="Ссылка",
                    ),
                ),
                (
                    "alt",
                    models.CharField(
                        default="Без описания", max_length=128, verbose_name="Описание"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.product",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="categories",
                to="catalog.subcategory",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(
                related_name="tags", to="catalog.tag", verbose_name="Тэги"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category",
                to="catalog.imagecategory",
                verbose_name="Изображение",
            ),
        ),
    ]
